TOSHIN_URL = "https://toushin-lib.fwg.ne.jp/FdsWeb/FDST030000/csv-file-download?isinCd=JP90C000GKC6&associFundCd="
DEFAULT_ENCODING = "utf-8"
TRUST_REGEXP = r"^[A-Z0-9]{8}$"
DATE_COLUMN_NAME = "Date"
TARGET_PRICE_COLUMN_NAME = "Close"
DIVIDEND_COLUMN_NAME = "Dividends"
DEFAULT_TIMEZONE = "Asia/Tokyo"
BUSINESS_DAYS_PER_YEAR = 246
SQUARED_BUSINESS_DAYS_PER_YEAR = 15.684387141358123  # sqrt(246)